flightsBtn="//a[@id='primary-header-flight']"
multiCityBtn="(//div[@class='col gcw-sub-nav-option-wrapper sub-nav-radio-button-for-high-contrast-mode'])[3]"
notifCloseBtn="(//span[@class='icon icon-close'])[2]"
adultAgeBtn="//select[@id='flight-adults-flp']"
adultAgeSelectBtn="(//option[@value='2'])[1]"
childrenBtn="//select[@id='flight-children-flp']"
childrenNumBtn="(//option[@value='2'])[2]"
child1AgeLabel="(//span[contains(text(), 'Child 1 age')])[1]"
children1AgeBtn="//select[@id='flight-age-select-1-flp']"
children1AgeSelectBtn="(//option[@value='10'])[1]"
children2AgeBtn="//select[@id='flight-age-select-2-flp']"
children2AgeSelectBtn="(//option[@value='6'])[4]"
addFlightBtn="//a[@class='secondary gcw-add-fields']"
source1Btn="(//input[@class='clear-btn-input gcw-storeable text gcw-origin gcw-required gcw-distinct-locations'])[1]"
source2Btn="(//input[@class='clear-btn-input gcw-storeable text gcw-origin multidest-field'])[1]"
source3Btn="(//input[@class='clear-btn-input gcw-storeable text gcw-origin multidest-field'])[2]"
destination1Btn="(//input[@class='clear-btn-input gcw-storeable text gcw-destination gcw-required gcw-distinct-locations'])[1]"
destination2Btn="(//input[@class='clear-btn-input gcw-storeable text gcw-destination multidest-field'])[1]"
destination3Btn="(//input[@class='clear-btn-input gcw-storeable text gcw-destination multidest-field'])[2]"
loc1And3Select="(//div[@class='multiLineDisplay details'])[2]"
loc2Select="(//div[@class='multiLineDisplay details'])[1]"
flight1DateBtn="//input[@id='flight-departing-single-flp']"
flight2DateBtn="//input[@id='flight-2-departing-flp']"
flight3DateBtn="//input[@id='flight-3-departing-flp']"
datesPicker="(//button[@class='datepicker-cal-date'])"
searchBtn="(//button[@class='btn-primary btn-action gcw-submit '])[1]"
flightsResult="(//div[@class='grid-container standard-padding '])"
nonstopFlightSelect="//input[@id='stopFilter_stops-0']"
onestopFlightSelect="//input[@id='stopFilter_stops-1']"
lowestPriceFlight="(//button[@class='btn-secondary btn-action t-select-btn'])[1]"
selectFareBtn="(//span[contains(text(), 'Select this fare')])[1]"
noExtraCostFlight="(//span[contains(text(), '+ $0.00')])[1]"
itineraryConfirmation="(//h2[contains(text(), 'Trip Summary')])[1]"
flight1Sourceconfirmation="((//div[@class='dateAndOD cf'])[1]//div[@class='airport type-300'])[1]"
flight1DestConfirmation="((//div[@class='dateAndOD cf'])[1]//div[@class='airport type-300'])[2]"
flight2Sourceconfirmation="((//div[@class='dateAndOD cf'])[2]//div[@class='airport type-300'])[1]"
flight2DestConfirmation="((//div[@class='dateAndOD cf'])[2]//div[@class='airport type-300'])[2]"
flight3Sourceconfirmation="((//div[@class='dateAndOD cf'])[3]//div[@class='airport type-300'])[1]"
flight3DestConfirmation="((//div[@class='dateAndOD cf'])[3]//div[@class='airport type-300'])[2]"